### ISSUE TITLE
wallet connect modal

### ISSUE THREAD

**Issue by jgeary** [ourzora/create-auction-house#22]
The default wallet connect modal has some styling issues.

<img width="552" alt="Screen Shot 2021-11-08 at 5 55 47 PM" src="https://user-images.githubusercontent.com/36774175/140831476-29926a9b-d222-47e8-b02f-2a3a9f69bd2c.png">

**Comment by iainnash** [comment]
What auction house is this on?

**Comment by iainnash** [comment]
<img width="609" alt="Screen Shot 2021-12-02 at 12 12 14 PM" src="https://user-images.githubusercontent.com/835896/144470143-85a8ba1f-5633-4b8c-b94c-63eea26a28e7.png">
Looks good on my end.
